flow_csv: 'data/river-flow-imputed-with-non-nans.csv'
clim_csv: 'data/daily-ts-means-per-station.csv'
other_csv: ''  
station_attrs: 'data/nrfa-station-metadata.csv'
station_attrs_cols: [
    "catchment-area",
    "saar-1961-1990",
    "lcm2007-urban",
    "bfihost",
    "farl",
    "dpsbar",
    "propwet"
]
adj_np: 'data/adj-mat-all-stations.csv'  
scaler: StandardScaler
model_name: 'Mamba'
  
  

hidden: 64
dropout: 0.1
horizon: 7
history: 7
mamba_d_state: 128
mamba_d_conv: 2
mamba_expand: 2

batch_size:  16
optimizer: adam
lr: 0.00001
weight_decay: 0.00001  
epochs: 100
patience: 10

num_runs: 10
start_seed: 42

results_dir: 'data/results/${model_name}-${other_csv}-h=${horizon}-and-l=${history}'
log_dir: 'data/logs/${model_name}-${other_csv}-h=${horizon}-and-l=${history}'

device: 'cuda'  
use_multi_gpu: True  
