adj_np: data/adj-mat-all-stations.csv
binary_adj: False
batch_size: 8
clim_csv: data/daily-ts-means-per-station.csv
device: cuda
epochs: 1000
flow_csv: data/river-flow-imputed-with-non-nans.csv
other_csv: ''
hidden: 32
history: 7
horizon: 7

results_dir: 'data/results/${model_name}-${other_csv}-binary=${binary_adj}-h=${horizon}-and-l=${history}'
log_dir: 'data/logs/${model_name}-${other_csv}-binary=${binary_adj}-h=${horizon}-and-l=${history}'
loss_function: mse
lr: 0.0001

num_runs: 10
optimizer: adam
patience: 10
start_seed: 42
scaler: StandardScaler
station_attrs: data/nrfa-station-metadata.csv
add_storage: False
use_packing: False
reg_4_loss: ''
model_name: 'TimeXer'
station_attrs_cols:
- catchment-area
- saar-1961-1990
- lcm2007-urban
- bfihost
- farl
- dpsbar
- propwet
test_ratio: 0.15
train_ratio: 0.7
use_multi_gpu: True
val_ratio: 0.15
weight_decay: 0.0001  

task_name: "short_term_forecast"
features: "M"              
patch_len: 1               
d_model: 32
d_ff: 128
n_heads: 2
dropout: 0.1
use_norm: False
e_layers: 1
embed: 'fixed'
freq: 'd'
factor: 3
activation: "elu"




